import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.scss";
import StoreProvider from './StoreProvider';
import FullScreenLoader from '@/components/masterLayout/FullScreenLoader';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <FullScreenLoader />
        {children}
        </StoreProvider>
      </body>
    </html>
  );
}
